databases:
  - name: microverse
    databaseName: microverse_cqxk
    user: microverse

services:
  - type: web
    name: fastpay
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microverse
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false