databases:
  - name: recipe_app
    databaseName: recipe_app_22k0
    user: recipe_app_22k0_user

services:
  - type: web
    name: fastpay
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false